### ISSUE TITLE
failed to allocate an alternative stack

### ISSUE THREAD

**Issue by Nugine** [Nugine/rlimit#1]
When I run the test, it sometimes panicked.
I am sure that it is related to `RLIMIT_AS`, but the limit (128MB, 256MB) is high enough. Why?
[src/test.rs#L13](https://github.com/Nugine/rlimit/blob/557e6a54e4e80b35017404965a0a26b7f64f33a7/src/test.rs#L13)

```bash
$ export RUST_BACKTRACE=1;cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/rlimit-5a874300cf08dd30

running 3 tests
test test::test_eq ... ok
test test::test_set_get ... ok
thread '<unnamed>' panicked at 'failed to allocate an alternative stack', src/libstd/sys/unix/stack_overflow.rs:136:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::begin_panic
             at src/libstd/panicking.rs:412
   6: std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/stack_overflow.rs:136
             at src/libstd/sys/unix/stack_overflow.rs:148
             at src/libstd/sys/unix/stack_overflow.rs:162
             at src/libstd/sys/unix/stack_overflow.rs:15
             at src/libstd/sys_common/thread.rs:11
             at src/libstd/sys/unix/thread.rs:81
   7: start_thread
   8: __clone
fatal runtime error: failed to initiate panic, error 5
error: process didn't exit successfully: `/home/nugine/project/rlimit/target/debug/deps/rlimit-5a874300cf08dd30` (signal: 6, SIGABRT: process abort signal)
```

**Comment by losfair** [comment]
`RLIMIT_AS` limits the size of **virtual memory** used, but not the actual size of physical memory used by the process itself.

Shared libraries (`libc`, for example), although not really taking up physical memory in processes dynamically linking to them, do occupy map entries and take up the virtual memory.

Techniques like `mprotect` tricks used in some places may also allocate gigabytes of virtual memory without using most of it.

**Comment by Nugine** [comment]
[Nugine/tester](https://github.com/Nugine/tester.git)
The tool shows that `cargo test` uses about 70 MB of memory (`ru_maxrss`). So I thought 128MB is enough. 
```bash
$ tester cargo -a=test
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running target/debug/deps/rlimit-5a874300cf08dd30

running 3 tests
test test::test_eq ... ok
test test::test_set_get ... ok
test test::test_get ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests rlimit

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

code: 0
real time: 130 ms
user time: 77 ms
sys time: 34 ms
memory: 69.461 MB
```

Insufficient virtual memory resource can cause unexpected problems which this crate can not handle.
Thank you for your help! @losfair
