### ISSUE TITLE
Test failure on 32bit

### ISSUE THREAD

**Issue by AdrianBunk** [Nugine/rlimit#30]
https://buildd.debian.org/status/logs.php?pkg=rust-rlimit&ver=0.7.0-1

```
test rlim::rlim_value ... FAILED

failures:

---- rlim::rlim_value stdout ----
thread 'rlim::rlim_value' panicked at 'assertion failed: `(left == right)`
  left: `"4294967295\n4294967295\n4294967295\n"`,
 right: `"18446744073709551615\n18446744073709551615\n18446744073709551615\n"`', tests/it/rlim.rs:45:5
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.57.0/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /usr/src/rustc-1.57.0/library/core/src/panicking.rs:100:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /usr/src/rustc-1.57.0/library/core/src/panicking.rs:138:5
   4: it::rlim::rlim_value
             at /usr/share/cargo/registry/rlimit-0.7.0/tests/it/rlim.rs:45:5
   5: it::rlim::rlim_value::{{closure}}
             at /usr/share/cargo/registry/rlimit-0.7.0/tests/it/rlim.rs:29:1
   6: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.57.0/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /usr/src/rustc-1.57.0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    rlim::rlim_value

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.35s
```

**Comment by Nugine** [comment]
This bug is caused by the mismatch between rust-lang/libc and the system header files. I will open a issue there.
